use super::html_escape;
use super::remote::{OAuthGuild, RemoteSession};

const PORTAL_CSS: &str = r#"
:root{--bg:#080b12;--panel:#111622;--panel2:#171d2b;--line:#252d3d;--ink:#f7f8fb;--muted:#98a2b5;--accent:#8b5cf6;--accent2:#22d3ee;--green:#34d399;--red:#fb7185;--gold:#fbbf24;--shadow:0 24px 70px rgba(0,0,0,.28)}
*{box-sizing:border-box}html{background:var(--bg);color:var(--ink);font-family:Pretendard,"Segoe UI","Malgun Gothic",sans-serif}body{margin:0;min-height:100vh;background:radial-gradient(circle at 8% 0%,rgba(139,92,246,.18),transparent 30%),radial-gradient(circle at 100% 20%,rgba(34,211,238,.10),transparent 28%),var(--bg)}
button,input,select,textarea{font:inherit}.shell{max-width:1540px;margin:0 auto;padding:24px}.topbar{display:flex;align-items:center;gap:18px;margin-bottom:20px}.brandmark{width:46px;height:46px;border-radius:15px;display:grid;place-items:center;background:linear-gradient(135deg,var(--accent),#6d28d9 55%,var(--accent2));font-size:23px;box-shadow:0 12px 30px rgba(139,92,246,.35)}.brandcopy strong{display:block;font-size:20px;letter-spacing:-.03em}.brandcopy span{font-size:12px;color:var(--muted)}.server-chip{display:flex;align-items:center;gap:10px;margin-left:16px;padding:8px 12px;border:1px solid var(--line);border-radius:13px;background:rgba(17,22,34,.8)}.server-icon,.avatar{width:32px;height:32px;border-radius:10px;object-fit:cover;background:#242b3a}.server-chip small{display:block;color:var(--muted)}.statusline{margin-left:auto;display:flex;align-items:center;gap:10px;color:var(--muted);font-size:13px}.dot{width:9px;height:9px;border-radius:50%;background:var(--red);box-shadow:0 0 0 4px rgba(251,113,133,.12)}.dot.on{background:var(--green);box-shadow:0 0 0 4px rgba(52,211,153,.12)}.userbox{display:flex;align-items:center;gap:9px;padding-left:12px;border-left:1px solid var(--line)}
.workspace{display:grid;grid-template-columns:minmax(0,1fr) 390px;gap:18px}.maincol,.chatcol{min-width:0}.panel{background:linear-gradient(180deg,rgba(23,29,43,.96),rgba(17,22,34,.96));border:1px solid var(--line);border-radius:20px;box-shadow:var(--shadow)}.searchbar{padding:16px;display:flex;gap:10px}.searchbar input{flex:1;border:1px solid var(--line);background:#0d111b;color:var(--ink);padding:13px 15px;border-radius:13px;outline:none}.searchbar input:focus{border-color:var(--accent);box-shadow:0 0 0 3px rgba(139,92,246,.16)}.searchbar select{background:#0d111b;color:var(--ink);border:1px solid var(--line);border-radius:13px;padding:0 12px}.btn{border:0;border-radius:12px;padding:11px 15px;font-weight:700;color:white;background:#293245;cursor:pointer;transition:.16s transform,.16s background,.16s opacity}.btn:hover:not(:disabled){transform:translateY(-1px);background:#354159}.btn:disabled{opacity:.4;cursor:not-allowed}.btn.primary{background:linear-gradient(135deg,var(--accent),#6d28d9)}.btn.primary:hover:not(:disabled){background:linear-gradient(135deg,#9d74ff,#7c3aed)}.btn.icon{padding:9px 11px}.btn.danger{background:rgba(251,113,133,.16);color:#fecdd3}.btn.ghost{background:transparent;border:1px solid var(--line);color:var(--muted)}
.search-results{display:none;padding:0 16px 16px;gap:10px}.search-results.open{display:grid}.result{display:grid;grid-template-columns:56px minmax(0,1fr) auto;align-items:center;gap:12px;padding:10px;border-radius:14px;background:#0d111b;border:1px solid var(--line)}.thumb{width:56px;height:56px;border-radius:11px;object-fit:cover;background:#242b3a}.title{font-weight:750;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.meta{color:var(--muted);font-size:12px;margin-top:4px}
.now{margin-top:18px;padding:20px}.now-grid{display:grid;grid-template-columns:120px minmax(0,1fr);gap:20px}.cover{width:120px;height:120px;border-radius:18px;object-fit:cover;background:linear-gradient(135deg,#272f42,#151a26)}.eyebrow{font-size:11px;letter-spacing:.14em;text-transform:uppercase;color:var(--accent2);font-weight:800}.now h1{font-size:25px;letter-spacing:-.04em;margin:6px 0 5px}.progress{height:7px;background:#293143;border-radius:99px;overflow:hidden;cursor:pointer;margin-top:18px}.progress>span{display:block;height:100%;width:0;background:linear-gradient(90deg,var(--accent),var(--accent2));border-radius:99px}.time{display:flex;justify-content:space-between;color:var(--muted);font-size:11px;margin-top:6px}.controls{display:flex;align-items:center;gap:9px;margin-top:13px;flex-wrap:wrap}.volume{display:flex;align-items:center;gap:7px;margin-left:auto}.volume input{width:110px;accent-color:var(--accent)}
.lyrics{margin-top:14px;border-top:1px solid var(--line);padding-top:14px}.lyrics-head{display:flex;align-items:center;justify-content:space-between}.lyrics-view{max-height:180px;overflow:auto;padding:12px 2px 4px;color:#cbd5e1;line-height:1.9;white-space:pre-wrap}.lyrics-line{padding:2px 9px;border-radius:8px;transition:.2s}.lyrics-line.active{background:rgba(139,92,246,.18);color:#fff;font-weight:750}.empty{padding:28px;text-align:center;color:var(--muted)}
.queue{margin-top:18px;padding:18px}.section-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:12px}.section-head h2{margin:0;font-size:18px}.queue-list{display:grid;gap:8px}.queue-item{display:grid;grid-template-columns:38px 48px minmax(0,1fr) auto auto;align-items:center;gap:11px;padding:10px 11px;border:1px solid transparent;border-radius:14px;background:#0d111b}.queue-item:hover{border-color:#313a4e}.rank{width:34px;height:34px;display:grid;place-items:center;border-radius:11px;background:#20283a;color:#cbd5e1;font-weight:800}.queue-item .thumb{width:48px;height:48px}.score{min-width:68px;text-align:center}.score strong{display:block;color:var(--gold);font-size:17px}.score span{font-size:10px;color:var(--muted)}.votes{display:flex;gap:5px}.vote{border:1px solid var(--line);background:#171e2c;color:#cbd5e1;border-radius:10px;padding:7px 9px;cursor:pointer}.vote.active{border-color:var(--accent);color:white;background:rgba(139,92,246,.2)}
.tabs{margin-top:18px;overflow:hidden}.tabbar{display:flex;gap:4px;border-bottom:1px solid var(--line);padding:10px 12px 0;overflow:auto}.tabbtn{border:0;background:transparent;color:var(--muted);font-weight:700;padding:11px 13px;cursor:pointer;border-bottom:2px solid transparent;white-space:nowrap}.tabbtn.active{color:white;border-color:var(--accent)}.tabbody{min-height:240px;padding:15px}.library-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(230px,1fr));gap:10px}.library-card{border:1px solid var(--line);background:#0d111b;border-radius:14px;padding:12px;display:flex;gap:11px;align-items:center}.library-card .thumb{width:50px;height:50px}.playlist{border:1px solid var(--line);background:#0d111b;border-radius:14px;padding:12px;margin-bottom:10px}.playlist-head,.toolbar{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.playlist-head .title{flex:1}.playlist-entry{display:flex;align-items:center;gap:8px;padding:8px 0 0 14px;color:#cbd5e1}.playlist-entry span{flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.audit-row{display:grid;grid-template-columns:135px 120px 130px minmax(0,1fr);gap:10px;padding:9px;border-bottom:1px solid var(--line);font-size:12px}.audit-row span:first-child{color:var(--muted)}
.chatcol{display:flex;flex-direction:column;height:calc(100vh - 108px);position:sticky;top:20px}.chat-head{padding:16px 17px;border-bottom:1px solid var(--line)}.chat-head h2{font-size:17px;margin:0}.chat-head p{font-size:12px;color:var(--muted);margin:4px 0 0}.messages{flex:1;overflow:auto;padding:14px}.message{display:grid;grid-template-columns:34px minmax(0,1fr);gap:9px;margin-bottom:14px}.message .avatar{width:34px;height:34px}.message-head{font-size:12px}.message-head strong{margin-right:6px}.message-head time{color:var(--muted)}.message-body{font-size:14px;line-height:1.55;margin-top:3px;word-break:break-word}.reaction-row{display:flex;gap:5px;margin-top:6px;flex-wrap:wrap}.reaction{border:1px solid var(--line);background:#1b2232;color:#dbe3f2;border-radius:99px;padding:4px 8px;font-size:11px;cursor:pointer}.reaction.active{border-color:var(--accent);background:rgba(139,92,246,.2)}.chat-compose{border-top:1px solid var(--line);padding:12px}.chat-compose textarea{width:100%;resize:none;background:#0d111b;color:white;border:1px solid var(--line);border-radius:13px;padding:11px;min-height:68px;outline:none}.compose-actions{display:flex;justify-content:space-between;align-items:center;margin-top:8px}.emoji-picks{display:flex;gap:4px}.emoji-picks button{background:transparent;border:0;font-size:17px;cursor:pointer}.toast-wrap{position:fixed;right:24px;bottom:24px;display:grid;gap:8px;z-index:99}.toast{background:#1b2434;border:1px solid #354159;color:white;padding:12px 15px;border-radius:12px;box-shadow:var(--shadow);max-width:360px}.toast.err{border-color:rgba(251,113,133,.55)}.modal{position:fixed;inset:0;background:rgba(3,5,10,.7);display:none;place-items:center;z-index:80;padding:20px}.modal.open{display:grid}.modal-card{width:min(560px,100%);max-height:88vh;overflow:auto;background:#121824;border:1px solid var(--line);border-radius:20px;padding:20px;box-shadow:var(--shadow)}.field{display:grid;gap:6px;margin:12px 0}.field label{font-size:12px;color:var(--muted)}.field input,.field select{background:#0d111b;border:1px solid var(--line);color:white;border-radius:11px;padding:10px}
.login-shell{min-height:100vh;display:grid;place-items:center;padding:24px}.login-card{width:min(560px,100%);background:rgba(17,22,34,.96);border:1px solid var(--line);border-radius:26px;padding:32px;box-shadow:var(--shadow);text-align:center}.login-logo{width:76px;height:76px;margin:0 auto 18px;border-radius:24px;display:grid;place-items:center;font-size:36px;background:linear-gradient(135deg,var(--accent),var(--accent2))}.login-card h1{margin:0;font-size:30px}.login-card p{color:var(--muted);line-height:1.65}.guild-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:12px;margin-top:24px;text-align:left}.guild-card{display:flex;align-items:center;gap:13px;padding:15px;border:1px solid var(--line);border-radius:16px;background:#0d111b;color:white;text-decoration:none}.guild-card:hover{border-color:var(--accent)}.setup-note{padding:14px;border-radius:13px;background:rgba(251,191,36,.08);border:1px solid rgba(251,191,36,.25);color:#fde68a;text-align:left;font-size:13px}.link{color:#c4b5fd;text-decoration:none}.mobile-only{display:none}
@media(max-width:980px){.shell{padding:14px}.workspace{grid-template-columns:1fr}.chatcol{position:static;height:620px}.server-chip{margin-left:0}.statusline{margin-left:auto}.now-grid{grid-template-columns:84px minmax(0,1fr)}.cover{width:84px;height:84px}.queue-item{grid-template-columns:34px 44px minmax(0,1fr) auto}.queue-item>.score{display:none}.topbar{flex-wrap:wrap}.userbox{display:none}}
@media(max-width:600px){.shell{padding:10px}.brandcopy span,.server-chip small{display:none}.server-chip{padding:6px}.statusline{font-size:0}.searchbar{flex-wrap:wrap}.searchbar input{width:100%;flex-basis:100%}.now{padding:15px}.now h1{font-size:19px}.volume{width:100%;margin:4px 0 0}.queue{padding:12px}.queue-item{grid-template-columns:30px minmax(0,1fr) auto}.queue-item>.thumb{display:none}.votes{flex-direction:column}.audit-row{grid-template-columns:1fr 1fr}.audit-row span:last-child{grid-column:1/-1}.desktop-only{display:none}.mobile-only{display:block}}
"#;

fn page(title: &str, body: &str) -> String {
    format!(
        r#"<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>{} · 마참뮤직</title><style>{}</style></head><body>{}</body></html>"#,
        html_escape(title),
        PORTAL_CSS,
        body
    )
}

pub fn login(configured: bool, dev_login: bool, message: Option<&str>) -> String {
    let action = if configured {
        r#"<a class="btn primary" data-testid="discord-login" href="/music/oauth/start">Discord로 계속하기</a>"#.to_string()
    } else {
        r#"<div class="setup-note"><strong>OAuth 설정이 필요합니다.</strong><br>MUSICBOT_DISCORD_CLIENT_ID, MUSICBOT_DISCORD_CLIENT_SECRET, MUSICBOT_PUBLIC_BASE_URL 환경변수를 설정한 뒤 재시작하세요.</div>"#.to_string()
    };
    let dev = if dev_login {
        r#"<form method="post" action="/music/dev-login" style="margin-top:12px"><button class="btn ghost" data-testid="dev-login" type="submit">로컬 검증 계정으로 입장</button></form>"#
    } else {
        ""
    };
    let message = message
        .map(|value| {
            format!(
                r#"<div class="setup-note" style="margin-bottom:15px">{}</div>"#,
                html_escape(value)
            )
        })
        .unwrap_or_default();
    page(
        "로그인",
        &format!(
            r#"<main class="login-shell"><section class="login-card"><div class="login-logo">♫</div><h1>마참뮤직</h1><p>Discord 서버의 음악을 함께 고르고, 투표하고,<br>한 화면에서 실시간으로 조작하세요.</p>{message}{action}{dev}<p style="font-size:12px;margin-top:24px">로그인하면 Discord 서버 멤버십과 권한을 확인합니다.<br><a class="link" href="/">운영자 패널로 이동</a></p></section></main>"#
        ),
    )
}

pub fn guild_selector(session: &RemoteSession, guilds: &[OAuthGuild]) -> String {
    let cards: String = guilds
        .iter()
        .map(|guild| {
            let icon = guild.icon_url().unwrap_or_default();
            format!(
                r#"<a class="guild-card" data-testid="guild-card" href="/music/guilds/{id}"><img class="server-icon" src="{icon}" alt=""><div><strong>{name}</strong><div class="meta">마참뮤직 리모컨 열기</div></div></a>"#,
                id = guild.id,
                icon = html_escape(&icon),
                name = html_escape(&guild.name),
            )
        })
        .collect();
    page(
        "서버 선택",
        &format!(
            r#"<main class="login-shell"><section class="login-card" style="width:min(900px,100%)"><div class="login-logo">♫</div><h1>어서 와요, {user}</h1><p>리모컨을 열 Discord 서버를 선택하세요. 서버별 좋아요와 보관함은 서로 분리됩니다.</p><div class="guild-grid">{cards}</div><form method="post" action="/music/logout" style="margin-top:20px"><input type="hidden" name="csrf" value="{csrf}"><button class="btn ghost" type="submit">로그아웃</button></form></section></main>"#,
            user = html_escape(&session.display_name),
            csrf = html_escape(&session.csrf_token),
        ),
    )
}

pub fn guild(session: &RemoteSession, guild: &OAuthGuild) -> String {
    let icon = guild.icon_url().unwrap_or_default();
    let avatar = session.avatar_url.clone().unwrap_or_default();
    let body = format!(
        r#"<div class="shell" data-testid="music-portal"><header class="topbar">
  <div class="brandmark">♫</div><div class="brandcopy"><strong>마참뮤직</strong><span>함께 고르는 서버 음악</span></div>
  <a class="server-chip" href="/music"><img class="server-icon" src="{icon}" alt=""><div><strong>{guild_name}</strong><small>서버 변경</small></div></a>
  <div class="statusline"><span id="liveDot" class="dot"></span><span id="liveText">연결 중</span><div class="userbox"><img class="avatar" src="{avatar}" alt=""><span>{user}</span></div></div>
  <button class="btn icon" id="settingsBtn" data-testid="settings-open" title="서버 설정">⚙</button>
</header>
<main class="workspace">
  <section class="maincol">
    <section class="panel searchbar"><input id="searchInput" data-testid="search-input" autocomplete="off" placeholder="곡, 아티스트 또는 URL 검색"><select id="provider"><option value="YouTube">YouTube</option><option value="YouTubeMusic">YouTube Music</option><option value="SoundCloud">SoundCloud</option></select><button class="btn primary" id="searchBtn" data-testid="search-submit">검색</button></section>
    <section id="searchResults" class="panel search-results" data-testid="search-results"></section>
    <section class="panel now" data-testid="now-playing"><div class="now-grid"><img id="cover" class="cover" alt="현재 곡"><div><div class="eyebrow" id="nowStatus">NOW PLAYING</div><h1 id="nowTitle">재생 중인 곡이 없습니다</h1><div class="meta" id="nowMeta">대기열에서 곡을 추가해 보세요.</div><div class="progress" id="progress" data-testid="seek-bar"><span id="progressFill"></span></div><div class="time"><span id="elapsed">0:00</span><span id="duration">0:00</span></div><div class="controls"><button class="btn icon" id="playPause" data-testid="play-pause">▶</button><button class="btn icon" id="skip" data-testid="skip">⏭</button><button class="btn ghost" id="lyricsToggle" data-testid="lyrics-toggle">가사</button><div class="volume"><span>🔊</span><input id="volume" data-testid="volume" type="range" min="0" max="200" value="100"><span id="volumeLabel">100%</span></div></div></div></div><div class="lyrics" id="lyricsBox" hidden><div class="lyrics-head"><strong>가사</strong><button class="btn ghost" id="lyricsMode">전체 보기</button></div><div class="lyrics-view" id="lyricsView">가사를 불러오는 중...</div></div></section>
    <section class="panel queue"><div class="section-head"><h2>대기열 <span class="meta" id="queueCount"></span></h2><span class="meta">점수순 · 등록순</span></div><div id="queueList" class="queue-list" data-testid="queue-list"></div></section>
    <section class="panel tabs"><div class="tabbar"><button class="tabbtn active" data-tab="recent">최근 곡</button><button class="tabbtn" data-tab="playlists">서버 재생목록</button><button class="tabbtn" data-tab="liked">좋아요</button><button class="tabbtn" data-tab="saved">보관함</button><button class="tabbtn" data-tab="audit">활동 로그</button></div><div class="tabbody" id="tabBody" data-testid="tab-body"></div></section>
  </section>
  <aside class="panel chatcol"><div class="chat-head"><h2># 서버 채팅</h2><p>Discord와 분리된 마참뮤직 전용 채팅</p></div><div class="messages" id="messages" data-testid="chat-messages"></div><div class="chat-compose"><textarea id="chatInput" data-testid="chat-input" maxlength="2000" placeholder="서버 멤버들과 이야기해 보세요"></textarea><div class="compose-actions"><div class="emoji-picks"><button data-emoji="👍">👍</button><button data-emoji="❤️">❤️</button><button data-emoji="🔥">🔥</button></div><button class="btn primary" id="chatSend" data-testid="chat-send">보내기</button></div></div></aside>
</main></div>
<div class="modal" id="settingsModal"><div class="modal-card"><div class="section-head"><h2>서버 리모컨 설정</h2><button class="btn ghost" id="settingsClose">닫기</button></div><div id="settingsBody"></div><button class="btn primary" id="settingsSave" data-testid="settings-save">설정 저장</button></div></div><div class="toast-wrap" id="toasts"></div>
<script>window.MACHAM={{guildId:"{guild_id}",csrf:"{csrf}"}};</script><script>{script}</script>"#,
        icon = html_escape(&icon),
        guild_name = html_escape(&guild.name),
        avatar = html_escape(&avatar),
        user = html_escape(&session.display_name),
        guild_id = guild.id,
        csrf = html_escape(&session.csrf_token),
        script = PORTAL_JS,
    );
    page(&guild.name, &body)
}

const PORTAL_JS: &str = r#"
const M=window.MACHAM;let state=null,searchResults=[],activeTab='recent',lyrics=null,lyricsFull=false,position=0,lastTick=Date.now(),refreshing=false;
const $=s=>document.querySelector(s);const h=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(message,error=false){const e=document.createElement('div');e.className='toast'+(error?' err':'');e.textContent=message;$('#toasts').append(e);setTimeout(()=>e.remove(),3600)}
async function api(path,options={}){options.headers={...(options.headers||{}),'X-CSRF-Token':M.csrf};if(options.body&&!options.headers['Content-Type'])options.headers['Content-Type']='application/json';const r=await fetch('/music/api/guilds/'+M.guildId+path,options);let data=null;try{data=await r.json()}catch{}if(!r.ok)throw new Error(data?.error||('요청 실패 ('+r.status+')'));return data}
const fmt=s=>{s=Math.max(0,Math.floor(Number(s)||0));return Math.floor(s/60)+':'+String(s%60).padStart(2,'0')};
function art(t){if(!t)return '';if(t.provider==='YouTube'||t.provider==='YouTubeMusic')return 'https://i.ytimg.com/vi/'+encodeURIComponent(t.contentId)+'/hqdefault.jpg';return ''}
async function refresh(){if(refreshing)return;refreshing=true;try{state=await api('/state');position=state.positionSeconds||0;lastTick=Date.now();render();$('#liveDot').classList.toggle('on',state.connection.botOnline);$('#liveText').textContent=!state.connection.botOnline?'봇 오프라인':state.connection.voiceConnected?'실시간 · 음성 연결':'실시간 · 음성 미연결'}catch(e){$('#liveDot').classList.remove('on');$('#liveText').textContent='연결 끊김';toast(e.message,true)}finally{refreshing=false}}
function render(){renderNow();renderQueue();renderChat();renderTab();if(!$('#settingsModal').classList.contains('open'))renderSettings()}
function renderNow(){const n=state.current;if(!n){$('#nowTitle').textContent='재생 중인 곡이 없습니다';$('#nowMeta').textContent=state.connection.voiceConnected?'대기열에서 곡을 추가해 보세요.':'봇이 음성 채널에 연결되면 재생할 수 있습니다.';$('#cover').removeAttribute('src');$('#nowStatus').textContent=state.connection.botOnline?'IDLE':'OFFLINE';$('#playPause').disabled=true;$('#skip').disabled=true;return}$('#nowTitle').textContent=n.track.title||n.track.contentId;$('#nowMeta').textContent=(n.track.artist||n.requestedByDisplay)+' · '+n.requestedByDisplay+'님의 신청곡';$('#cover').src=art(n.track);$('#nowStatus').textContent=state.player.isPaused?'PAUSED':'NOW PLAYING';$('#playPause').textContent=state.player.isPaused?'▶':'⏸';const unavailable=!state.connection.botOnline||!state.connection.voiceConnected;$('#playPause').disabled=!state.permissions.playback||unavailable;$('#skip').disabled=!state.permissions.playback||unavailable;$('#playPause').title=unavailable?'봇이 음성 채널에 연결되어 있지 않습니다.':state.permissions.playback?'':'재생 제어 권한이 없습니다.';$('#skip').title=$('#playPause').title;$('#volume').disabled=!state.permissions.volume||unavailable;$('#progress').title=!state.permissions.seek?'탐색 권한이 없습니다.':'';$('#volume').min=state.settings.minVolume;$('#volume').max=state.settings.maxVolume;$('#volume').value=state.player.effectiveVolume;$('#volumeLabel').textContent=state.player.effectiveVolume+'%';tickProgress()}
function tickProgress(){if(!state?.current)return;const playing=!state.player.isPaused;if(playing){const now=Date.now();position+=(now-lastTick)/1000;lastTick=now}else lastTick=Date.now();const total=state.current.durationSeconds||0;position=Math.min(position,total||position);$('#elapsed').textContent=fmt(position);$('#duration').textContent=fmt(total);$('#progressFill').style.width=(total?Math.min(100,position/total*100):0)+'%';highlightLyrics()}
setInterval(tickProgress,500);
function renderQueue(){const list=$('#queueList');$('#queueCount').textContent='('+state.queue.length+')';if(!state.queue.length){list.innerHTML='<div class="empty">다음 곡을 검색해 추가해 보세요.</div>';return}list.innerHTML=state.queue.map((q,i)=>`<article class="queue-item" data-testid="queue-item"><div class="rank">${i+1}</div><img class="thumb" src="${h(art(q.track))}" alt=""><div><div class="title">${h(q.track.title||q.track.contentId)}</div><div class="meta">${h(q.requestedByDisplay)} · 대기 ${q.score.waitScore} · 좋아요 ${q.score.likeCount} · 슈퍼 ${q.score.superLikeCount}${q.score.manualPriority!=null?' · 관리자 우선':''}</div></div><div class="score"><strong>${q.score.totalScore}</strong><span>POINT</span></div><div class="votes"><button class="vote ${q.myVote==='like'?'active':''}" data-vote="like" data-id="${h(q.id)}" ${!state.permissions.vote||q.isMine?'disabled':''}>♥ ${q.score.likeCount}</button><button class="vote ${q.myVote==='superLike'?'active':''}" data-vote="superLike" data-id="${h(q.id)}" ${!state.permissions.vote||q.isMine?'disabled':''}>★ ${q.score.superLikeCount}</button>${state.permissions.admin?`<button class="vote" data-pin="${h(q.id)}" title="관리자 우선">📌</button>`:''}${(q.isMine||state.permissions.admin)?`<button class="vote" data-remove="${h(q.id)}" title="제거">✕</button>`:''}</div></article>`).join('')}
function libraryCard(x,kind){const t=x.track||x;const meta=kind==='recent'?`${x.playedUtc.replace('T',' ').slice(0,16)} · ${x.requestedByDisplay} · ${x.endReason}`:(t.artist||t.provider);return `<div class="library-card"><img class="thumb" src="${h(art(t))}" alt=""><div style="min-width:0;flex:1"><div class="title">${h(t.title||t.contentId)}</div><div class="meta">${h(meta)}</div></div><button class="btn icon" data-requeue='${h(JSON.stringify(t))}' title="대기열에 추가">＋</button>${state.playlists.length?`<button class="btn ghost" data-add-to-playlist='${h(JSON.stringify(t))}'>목록</button>`:''}${kind==='saved'?`<button class="btn ghost" data-unsave='${h(JSON.stringify(t))}'>삭제</button>`:''}</div>`}
function filterLibrary(items,q){const needle=String(q||'').toLowerCase();return items.filter(x=>{const t=x.track||x;return !needle||[t.title,t.artist,t.provider].join(' ').toLowerCase().includes(needle)})}
function playlistMarkup(p){const canEdit=state.permissions.admin||p.isMine;const entries=(p.entries||[]).map((entry,i)=>entry.track?`<div class="playlist-entry"><span>${h(entry.track.title||entry.track.contentId)}</span><button class="vote" data-playlist-add-track="${p.id}" data-track='${h(JSON.stringify(entry.track))}'>대기열</button>${canEdit?`<button class="vote" data-playlist-remove="${p.id}" data-index="${i}">삭제</button>`:''}</div>`:'').join('');return `<div class="playlist" data-testid="playlist-card"><div class="playlist-head"><div class="title">${h(p.name)}</div><span class="meta">${p.entryCount}곡</span><button class="btn ghost" data-playlist-enqueue="${p.id}">전체 재등록</button>${canEdit?`<button class="vote" data-playlist-rename="${p.id}" data-name="${h(p.name)}">이름 변경</button><button class="vote" data-playlist-delete="${p.id}">삭제</button>`:''}</div>${entries||'<div class="meta" style="padding:10px 0 0 14px">아직 곡이 없습니다.</div>'}</div>`}
function renderTab(){const b=$('#tabBody');document.querySelectorAll('.tabbtn').forEach(x=>x.classList.toggle('active',x.dataset.tab===activeTab));if(activeTab==='recent')b.innerHTML=state.recent.length?'<div class="library-grid">'+state.recent.map(x=>libraryCard(x,'recent')).join('')+'</div>':'<div class="empty">최근 재생 기록이 없습니다.</div>';if(activeTab==='liked')b.innerHTML=`<div class="field"><input id="libraryFilter" data-testid="library-filter" placeholder="좋아요 검색"></div><div id="libraryRows" class="library-grid">${filterLibrary(state.liked,'').map(x=>libraryCard(x,'liked')).join('')}</div>`;if(activeTab==='saved')b.innerHTML=`<div class="field"><input id="libraryFilter" data-testid="library-filter" placeholder="보관함 검색"></div><div id="libraryRows" class="library-grid">${filterLibrary(state.saved,'').map(x=>libraryCard(x,'saved')).join('')}</div>`;if(activeTab==='playlists')b.innerHTML=`<div class="toolbar" style="margin-bottom:12px"><button class="btn primary" data-playlist-create ${!state.permissions.playlistEdit?'disabled':''}>새 재생목록</button><span class="meta">검색 결과나 보관함의 곡을 재생목록에 담을 수 있습니다.</span></div>`+(state.playlists.length?state.playlists.map(playlistMarkup).join(''):'<div class="empty">서버 재생목록이 없습니다.</div>');if(activeTab==='audit'){const reports=state.permissions.admin&&state.chatReports.length?`<div class="setup-note"><strong>미처리 채팅 신고</strong>${state.chatReports.filter(r=>!r.resolvedUtc).map(r=>`<div class="audit-row"><span>${h(r.createdUtc.replace('T',' ').slice(0,16))}</span><strong>${h(r.reporterDisplayName)}</strong><span>${h(r.messageAuthor)}</span><span>${h(r.reason)} · ${h(r.messageContent)} <button class="vote" data-report-resolve="${r.id}">처리</button></span></div>`).join('')}</div>`:'';b.innerHTML=`<div class="field"><input id="auditFilter" data-testid="audit-filter" placeholder="사용자·동작·기간·곡 제목 필터"></div>${reports}<div id="auditRows">${auditRows('')}</div>`}}
function auditRows(q){const needle=String(q||'').toLowerCase();const rows=state.audit.filter(a=>!needle||[a.displayName,a.action,a.target,a.afterValue,a.failureReason].join(' ').toLowerCase().includes(needle));return rows.length?rows.map(a=>`<div class="audit-row"><span>${h(a.createdUtc.replace('T',' ').slice(0,16))}</span><strong>${h(a.displayName)}</strong><span>${h(a.action)}</span><span>${h(a.target||a.afterValue||a.failureReason||'')}</span></div>`).join(''):'<div class="empty">조건에 맞는 활동 기록이 없습니다.</div>'}
function renderChat(){const m=$('#messages');if(!state.settings.chatEnabled){m.innerHTML='<div class="empty">관리자가 채팅을 껐습니다.</div>';$('#chatSend').disabled=true;return}$('#chatSend').disabled=!state.permissions.chat;m.innerHTML=state.chat.map(x=>`<div class="message"><img class="avatar" src="${h(x.avatarUrl||'')}" alt=""><div><div class="message-head"><strong>${h(x.displayName)}</strong><time>${h(x.createdUtc.replace('T',' ').slice(11,16))}</time>${(x.isMine||state.permissions.admin)&&!x.deletedUtc?` <button class="vote" data-chat-delete="${x.id}">삭제</button>`:''}${!x.isMine&&!x.deletedUtc?` <button class="vote" data-chat-report="${x.id}">신고</button>`:''}</div><div class="message-body">${x.deletedUtc?'<span class="meta">삭제된 메시지입니다.</span>':h(x.content)}</div><div class="reaction-row">${x.reactions.map(r=>`<button class="reaction ${r.reactedByMe?'active':''}" data-react="${x.id}" data-emoji="${h(r.emoji)}">${h(r.emoji)} ${r.count}</button>`).join('')}${!x.deletedUtc?`<button class="reaction" data-react="${x.id}" data-emoji="👍">＋</button>`:''}</div></div></div>`).join('');m.scrollTop=m.scrollHeight}
function renderSettings(){if(!state)return;const s=state.settings;const rule=(id,label,value)=>`<div class="field"><label>${label}</label><select id="${id}">${rules(value)}</select></div>`;$('#settingsBody').innerHTML=`<div class="field"><label>최소 / 최대 / 기본 볼륨</label><div class="toolbar"><input id="setMinVolume" type="number" min="0" max="200" value="${s.minVolume}"><input id="setMaxVolume" type="number" min="0" max="200" value="${s.maxVolume}"><input id="setDefaultVolume" type="number" min="0" max="200" value="${s.defaultVolume}"></div></div><div class="field"><label>사용자 / 서버 대기열 최대 곡 수</label><div class="toolbar"><input id="setMaxUser" type="number" min="1" max="100" value="${s.maxQueuePerUser}"><input id="setMaxGuild" type="number" min="1" max="1000" value="${s.maxQueuePerGuild}"></div></div><div class="field"><label>허용 곡 길이(초)</label><input id="setMaxTrack" type="number" min="60" max="86400" value="${s.maxTrackSeconds}"></div><div class="field"><label>활동 로그 보존 일수</label><input id="setAuditDays" type="number" min="1" max="3650" value="${s.auditRetentionDays}"></div><div class="field"><label>지정 관리·기능 역할 ID (쉼표 구분)</label><input id="setRoleIds" value="${h((s.configuredRoleIds||[]).join(','))}"></div><div class="field"><label><input id="setChatEnabled" type="checkbox" ${s.chatEnabled?'checked':''}> 웹 채팅 사용</label></div>${rule('setSearchRule','검색·곡 등록 권한',s.searchRule)}${rule('setVoteRule','좋아요·슈퍼좋아요 권한',s.voteRule)}${rule('setChatRule','채팅 권한',s.chatRule)}${rule('setPlaybackRule','재생·스킵 권한',s.playbackRule)}${rule('setSeekRule','탐색 권한',s.seekRule)}${rule('setVolumeRule','볼륨 권한',s.volumeRule)}${rule('setQueueRule','대기열·재생목록 편집 권한',s.queueEditRule)}`;$('#settingsSave').hidden=!state.permissions.admin}
function rules(selected){return [['guildMember','길드 멤버'],['sameVoiceChannel','같은 음성 채널'],['configuredRole','지정 역할'],['administrator','관리자'],['disabled','사용 안 함']].map(([v,t])=>`<option value="${v}" ${selected===v?'selected':''}>${t}</option>`).join('')}
async function doSearch(){const q=$('#searchInput').value.trim();if(!q)return;$('#searchBtn').disabled=true;try{const d=await api('/search?q='+encodeURIComponent(q)+'&provider='+encodeURIComponent($('#provider').value));searchResults=d.results;const box=$('#searchResults');box.classList.add('open');const rows=d.results.length?d.results.map((t,i)=>`<div class="result"><img class="thumb" src="${h(art(t))}" alt=""><div><div class="title">${h(t.title||t.contentId)}</div><div class="meta">${h(t.artist||t.provider)} · ${t.durationLabel||'길이 미상'}</div></div><div><button class="btn primary" data-add="${i}">추가</button> <button class="btn ghost" data-save="${i}">보관</button>${state.playlists.length?` <button class="btn ghost" data-result-playlist="${i}">목록</button>`:''}</div></div>`).join(''):'<div class="empty">검색 결과가 없습니다.</div>';box.innerHTML=`<div class="section-head"><strong>검색 결과</strong><button class="btn ghost" data-search-close>닫기</button></div>${rows}`}catch(e){toast(e.message,true)}finally{$('#searchBtn').disabled=false}}
async function playlistAction(action,data={}){try{await api('/playlists/action',{method:'POST',body:JSON.stringify({action,...data})});toast('재생목록을 반영했습니다.');await refresh()}catch(e){toast(e.message,true)}}
function choosePlaylist(track){if(!state.playlists.length){toast('먼저 서버 재생목록을 만들어 주세요.',true);return}const lines=state.playlists.map((p,i)=>`${i+1}. ${p.name}`).join('\n');const picked=Number(prompt('곡을 담을 재생목록 번호를 입력하세요.\n'+lines));if(picked>=1&&picked<=state.playlists.length)playlistAction('addTrack',{playlistId:state.playlists[picked-1].id,track})}
async function enqueue(track){try{const result=await api('/queue',{method:'POST',body:JSON.stringify({track})});toast(result.playingNow?'바로 재생을 시작했습니다.':`대기열 ${result.queuePosition}번에 추가했습니다. (초기 0점)`);await refresh()}catch(e){toast(e.message,true)}}
async function control(action,value){try{await api('/control',{method:'POST',body:JSON.stringify({action,value,expectedItemId:state?.current?.id||null})});await refresh()}catch(e){toast(e.message,true);await refresh()}}
async function loadLyrics(){if(!state.current)return;$('#lyricsBox').hidden=false;$('#lyricsView').textContent='가사를 찾는 중...';try{lyrics=await api('/lyrics');renderLyrics()}catch(e){$('#lyricsView').textContent=e.message}}
function renderLyrics(){const v=$('#lyricsView');if(!lyrics||(!lyrics.plainText&&!lyrics.syncedLines.length)){v.textContent='이 곡의 가사를 찾지 못했습니다.';return}if(!lyricsFull&&lyrics.syncedLines.length){v.innerHTML=lyrics.syncedLines.map((l,i)=>`<div class="lyrics-line" data-ms="${l.startMs}" data-line="${i}">${h(l.text)}</div>`).join('')}else v.textContent=lyrics.plainText||lyrics.syncedLines.map(l=>l.text).join('\n');highlightLyrics()}
function highlightLyrics(){if(!lyrics||lyricsFull||!lyrics.syncedLines.length)return;let active=-1;for(let i=0;i<lyrics.syncedLines.length;i++)if(lyrics.syncedLines[i].startMs<=position*1000)active=i;document.querySelectorAll('.lyrics-line').forEach((x,i)=>{x.classList.toggle('active',i===active);if(i===active)x.scrollIntoView({block:'center',behavior:'smooth'})})}
$('#searchBtn').onclick=doSearch;$('#searchInput').onkeydown=e=>{if(e.key==='Enter')doSearch()};$('#playPause').onclick=()=>control(state.player.isPaused?'resume':'pause');$('#skip').onclick=()=>control('skip');$('#volume').onchange=e=>control('volume',Number(e.target.value));$('#volume').oninput=e=>$('#volumeLabel').textContent=e.target.value+'%';$('#progress').onclick=e=>{if(!state.permissions.seek||!state.current)return;const r=e.currentTarget.getBoundingClientRect();control('seek',(e.clientX-r.left)/r.width*(state.current.durationSeconds||0))};$('#lyricsToggle').onclick=loadLyrics;$('#lyricsMode').onclick=()=>{lyricsFull=!lyricsFull;$('#lyricsMode').textContent=lyricsFull?'현재 가사':'전체 보기';renderLyrics()};
$('#searchResults').onclick=e=>{const add=e.target.closest('[data-add]'),save=e.target.closest('[data-save]'),pl=e.target.closest('[data-result-playlist]'),close=e.target.closest('[data-search-close]');if(add)enqueue(searchResults[Number(add.dataset.add)]);if(save)api('/library',{method:'POST',body:JSON.stringify({track:searchResults[Number(save.dataset.save)],kind:'saved',present:true})}).then(()=>{toast('보관함에 저장했습니다.');refresh()}).catch(x=>toast(x.message,true));if(pl)choosePlaylist(searchResults[Number(pl.dataset.resultPlaylist)]);if(close)$('#searchResults').classList.remove('open')};
$('#queueList').onclick=e=>{const v=e.target.closest('[data-vote]'),pin=e.target.closest('[data-pin]'),remove=e.target.closest('[data-remove]');if(v)api('/vote',{method:'POST',body:JSON.stringify({itemId:v.dataset.id,kind:v.classList.contains('active')?null:v.dataset.vote})}).then(refresh).catch(x=>toast(x.message,true));if(pin)api('/queue/action',{method:'POST',body:JSON.stringify({action:'togglePin',itemId:pin.dataset.pin})}).then(refresh).catch(x=>toast(x.message,true));if(remove&&confirm('이 곡을 대기열에서 제거할까요?'))api('/queue/action',{method:'POST',body:JSON.stringify({action:'remove',itemId:remove.dataset.remove})}).then(refresh).catch(x=>toast(x.message,true))};
document.querySelector('.tabbar').onclick=e=>{const b=e.target.closest('[data-tab]');if(b){activeTab=b.dataset.tab;renderTab()}};$('#tabBody').onclick=e=>{const q=e.target.closest('[data-requeue]'),u=e.target.closest('[data-unsave]'),add=e.target.closest('[data-add-to-playlist]'),create=e.target.closest('[data-playlist-create]'),rename=e.target.closest('[data-playlist-rename]'),del=e.target.closest('[data-playlist-delete]'),remove=e.target.closest('[data-playlist-remove]'),enqueueAll=e.target.closest('[data-playlist-enqueue]'),enqueueTrack=e.target.closest('[data-playlist-add-track]'),resolve=e.target.closest('[data-report-resolve]');if(q)enqueue(JSON.parse(q.dataset.requeue));if(u)api('/library',{method:'POST',body:JSON.stringify({track:JSON.parse(u.dataset.unsave),kind:'saved',present:false})}).then(refresh).catch(x=>toast(x.message,true));if(add)choosePlaylist(JSON.parse(add.dataset.addToPlaylist));if(create){const name=prompt('새 재생목록 이름');if(name)playlistAction('create',{name})}if(rename){const name=prompt('새 이름',rename.dataset.name);if(name)playlistAction('rename',{playlistId:Number(rename.dataset.playlistRename),name})}if(del&&confirm('이 재생목록을 삭제할까요?'))playlistAction('delete',{playlistId:Number(del.dataset.playlistDelete)});if(remove&&confirm('이 곡을 재생목록에서 삭제할까요?'))playlistAction('removeEntry',{playlistId:Number(remove.dataset.playlistRemove),entryIndex:Number(remove.dataset.index)});if(enqueueAll)playlistAction('enqueue',{playlistId:Number(enqueueAll.dataset.playlistEnqueue)});if(enqueueTrack)enqueue(JSON.parse(enqueueTrack.dataset.track));if(resolve)api('/chat/report',{method:'POST',body:JSON.stringify({messageId:0,reason:'resolved',resolve:true,reportId:Number(resolve.dataset.reportResolve)})}).then(refresh).catch(x=>toast(x.message,true))};
$('#tabBody').oninput=e=>{if(e.target.id==='auditFilter')$('#auditRows').innerHTML=auditRows(e.target.value);if(e.target.id==='libraryFilter'){const items=activeTab==='liked'?state.liked:state.saved;$('#libraryRows').innerHTML=filterLibrary(items,e.target.value).map(x=>libraryCard(x,activeTab)).join('')}};
$('#chatSend').onclick=async()=>{const content=$('#chatInput').value.trim();if(!content)return;try{await api('/chat',{method:'POST',body:JSON.stringify({content})});$('#chatInput').value='';await refresh()}catch(e){toast(e.message,true)}};document.querySelector('.emoji-picks').onclick=e=>{if(e.target.dataset.emoji)$('#chatInput').value+=e.target.dataset.emoji};$('#messages').onclick=e=>{const r=e.target.closest('[data-react]'),d=e.target.closest('[data-chat-delete]'),report=e.target.closest('[data-chat-report]');if(r)api('/chat/reaction',{method:'POST',body:JSON.stringify({messageId:Number(r.dataset.react),emoji:r.dataset.emoji})}).then(refresh);if(d&&confirm('메시지를 삭제할까요?'))api('/chat/delete',{method:'POST',body:JSON.stringify({messageId:Number(d.dataset.chatDelete)})}).then(refresh);if(report){const reason=prompt('신고 사유를 입력하세요.');if(reason)api('/chat/report',{method:'POST',body:JSON.stringify({messageId:Number(report.dataset.chatReport),reason})}).then(()=>toast('신고했습니다.')).catch(x=>toast(x.message,true))}};
$('#settingsBtn').onclick=()=>$('#settingsModal').classList.add('open');$('#settingsClose').onclick=()=>$('#settingsModal').classList.remove('open');$('#settingsSave').onclick=async()=>{try{const roleIds=$('#setRoleIds').value.split(',').map(x=>Number(x.trim())).filter(x=>Number.isSafeInteger(x)&&x>0);await api('/settings',{method:'POST',body:JSON.stringify({minVolume:Number($('#setMinVolume').value),maxVolume:Number($('#setMaxVolume').value),defaultVolume:Number($('#setDefaultVolume').value),chatEnabled:$('#setChatEnabled').checked,searchRule:$('#setSearchRule').value,voteRule:$('#setVoteRule').value,chatRule:$('#setChatRule').value,playbackRule:$('#setPlaybackRule').value,seekRule:$('#setSeekRule').value,volumeRule:$('#setVolumeRule').value,queueEditRule:$('#setQueueRule').value,configuredRoleIds:roleIds,maxQueuePerUser:Number($('#setMaxUser').value),maxQueuePerGuild:Number($('#setMaxGuild').value),maxTrackSeconds:Number($('#setMaxTrack').value),auditRetentionDays:Number($('#setAuditDays').value)})});$('#settingsModal').classList.remove('open');toast('서버 설정을 저장했습니다.');await refresh()}catch(e){toast(e.message,true)}};
function connect(){const proto=location.protocol==='https:'?'wss':'ws';const ws=new WebSocket(proto+'://'+location.host+'/music/api/guilds/'+M.guildId+'/events');ws.onopen=()=>{$('#liveDot').classList.add('on');$('#liveText').textContent='실시간 연결'};ws.onmessage=()=>refresh();ws.onclose=()=>{$('#liveDot').classList.remove('on');$('#liveText').textContent='재연결 중';setTimeout(connect,1600)}}
refresh();connect();
"#;
